export type AgentUserType = {
	id                 :number,
	uuid               :string,
	referral_code      :string,
	name               :string,
	postal_code        :string,
	address1           :string,
	address2           :string,
	address3           :string,
	address4           :string,
	phone_number       :string,
	email              :string,
	login_id           :string,
	password           :string,
	bank_name          :string,
	bank_name_type	   :string,
	bank_code		   :string,
	branch_name        :string,
	branch_name_type   :string,
	branch_code        :string,
	bank_type          :string,
	bank_number        :string,
	bank_account       :string,
}

